--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.common_pb')

SEX = protobuf.EnumDescriptor();
SEX_FEMALE_ENUM = protobuf.EnumValueDescriptor();
SEX_MALE_ENUM = protobuf.EnumValueDescriptor();
HEADER = protobuf.Descriptor();
HEADER_CMD_FIELD = protobuf.FieldDescriptor();
HEADER_SEQ_FIELD = protobuf.FieldDescriptor();

SEX_FEMALE_ENUM.name = "FeMale"
SEX_FEMALE_ENUM.index = 0
SEX_FEMALE_ENUM.number = 0
SEX_MALE_ENUM.name = "Male"
SEX_MALE_ENUM.index = 1
SEX_MALE_ENUM.number = 1
SEX.name = "Sex"
SEX.full_name = ".Sex"
SEX.values = {SEX_FEMALE_ENUM,SEX_MALE_ENUM}
HEADER_CMD_FIELD.name = "cmd"
HEADER_CMD_FIELD.full_name = ".Header.cmd"
HEADER_CMD_FIELD.number = 1
HEADER_CMD_FIELD.index = 0
HEADER_CMD_FIELD.label = 2
HEADER_CMD_FIELD.has_default_value = false
HEADER_CMD_FIELD.default_value = 0
HEADER_CMD_FIELD.type = 5
HEADER_CMD_FIELD.cpp_type = 1

HEADER_SEQ_FIELD.name = "seq"
HEADER_SEQ_FIELD.full_name = ".Header.seq"
HEADER_SEQ_FIELD.number = 2
HEADER_SEQ_FIELD.index = 1
HEADER_SEQ_FIELD.label = 2
HEADER_SEQ_FIELD.has_default_value = false
HEADER_SEQ_FIELD.default_value = 0
HEADER_SEQ_FIELD.type = 5
HEADER_SEQ_FIELD.cpp_type = 1

HEADER.name = "Header"
HEADER.full_name = ".Header"
HEADER.nested_types = {}
HEADER.enum_types = {}
HEADER.fields = {HEADER_CMD_FIELD, HEADER_SEQ_FIELD}
HEADER.is_extendable = false
HEADER.extensions = {}

FeMale = 0
Header = protobuf.Message(HEADER)
Male = 1

